### PR TITLE
Elena/Edu - Add classes to change visibility for XS and S

### PR DESCRIPTION
**Pull request by ealmasque**

### CODE REVIEW

**Comment by rowantower** [comment]
Hi Elena&Edu!
The `$vieportXS` equals 0 so the`mqminmax($viewportXS - 1, $viewportS - 1)` is from 0 to 320px which is the extreme small device size which we do not support in general.

What is the problem you are trying to solve with this? Also what styles are you missing here https://scout24.github.io/showcar-ui/#utilities-target
(please scroll till `Visible/hidden classes` )

**Comment by ealmasque** [comment]
Hi @rowantower, 

We wanted to hide a component on all sizes except 'large' and 'extra-large', and we noticed that if we reduce the viewport size, the element appears again in XS, L and XL. We would like to hide it in XS.
Is there a way to do this in the current version of showcar-ui? We really don't want it to appear, particularly because we don't support such a small screen.

The showcar-ui library should support us in hiding this, right?

**Comment by inakianduaga** [comment]
@rowantower This is something I also run to previously. I'm also pro adding the style so it works consistently in `xs` viewports, even if those are not "officially" supported

**Comment by ealmasque** [comment]
Makes sense.
What would it take to add it?

**Comment by rowantower** [comment]
Then I'll better propose to adjust `sc-hidden-at-s` to work from 0 breakpoint rather than create a new class. In this way `s` will cover everything from 0 to 767px.
Otherwise it will create an illusion of support of extra small screens

**Comment by ealmasque** [comment]
This can be closed. Can someone review: 
https://github.com/Scout24/showcar-ui/pull/155

Thanks,

**Pull request closed without merging**
